/**
 * orchestrator-tools MCP Server
 *
 * 把 project-orchestrator-bundle 的 15 个子 Skill 的核心入口封装为 MCP Tool。
 * 让 Skills 可以被任何 MCP Host（Trae / Claude Code / Cursor / VS Code）调用。
 *
 * 协议：MCP 2026-07-28（无状态核心）
 * 传输：stdio（推荐）或 Streamable HTTP
 *
 * 关键设计：每个 Tool 通过子进程调用对应 Skill 的 CLI（统一接口）。
 * Skill CLI 独立维护，orchestrator-tools 仅负责参数转发与结果聚合。
 *
 * @generated by project-orchestrator-bundle / mcp-integration
 * @date 2026-08-24
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { exec } from 'child_process';
import { promisify } from 'util';
import { existsSync, statSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname, join } from 'path';

const execAsync = promisify(exec);

// ============================================================
// 环境配置
// ============================================================

const PROJECT_ROOT = process.env.PROJECT_ROOT || process.cwd();
const SKILL_BUNDLE_PATH = process.env.SKILL_BUNDLE_PATH ||
  resolve(PROJECT_ROOT, '.trae/skills/project-orchestrator-bundle');
const SKILL_CLI_BIN = process.env.SKILL_CLI_BIN ||
  resolve(SKILL_BUNDLE_PATH, 'dist/skill-cli.js');

// Skill CLI 默认超时（可被各 Tool 覆盖）
const DEFAULT_TIMEOUT_MS = 120_000;

// ❗️ 所有日志写到 stderr（stdio server 不能写 stdout）
const log = (msg: string) => console.error(`[orchestrator-tools] ${msg}`);

// ============================================================
// 通用：调用 Skill CLI 的核心函数
// ============================================================

interface SkillResult<T = any> {
  ok: boolean;
  command: string;
  data?: T;
  error?: string;
  warnings?: string[];
  nextActions?: string[];
  duration?: number;
}

async function callSkill(
  skill: string,
  command: string,
  input: Record<string, any>,
  options: { timeoutMs?: number; cwd?: string } = {}
): Promise<SkillResult> {
  const startTime = Date.now();
  const timeout = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const cwd = options.cwd ?? PROJECT_ROOT;

  // 检查 Skill CLI 是否存在
  if (!existsSync(SKILL_CLI_BIN)) {
    return {
      ok: false,
      command: `${skill}.${command}`,
      error: `Skill CLI not found at ${SKILL_CLI_BIN}. ` +
        `Build it first: cd ${SKILL_BUNDLE_PATH} && pnpm build`,
    };
  }

  const inputJson = JSON.stringify(input);
  const cmd = `node "${SKILL_CLI_BIN}" ${skill} ${command} ` +
    `--input '${inputJson.replace(/'/g, "'\\''")}' ` +
    `--project-root "${cwd}"`;

  try {
    const { stdout, stderr } = await execAsync(cmd, {
      cwd: PROJECT_ROOT,
      timeout,
      maxBuffer: 50 * 1024 * 1024, // 50MB
    });

    const result: SkillResult = JSON.parse(stdout);
    result.duration = Date.now() - startTime;

    if (stderr) {
      log(`[${skill}.${command}] stderr: ${stderr.slice(0, 500)}`);
    }

    return result;
  } catch (err: any) {
    log(`[${skill}.${command}] FAILED: ${err.message}`);

    // 尝试解析 stdout 中的错误 JSON（即使 exit code 非 0）
    if (err.stdout) {
      try {
        const partial = JSON.parse(err.stdout);
        partial.ok = false;
        partial.duration = Date.now() - startTime;
        return partial;
      } catch {
        // 不是 JSON，直接返回错误
      }
    }

    return {
      ok: false,
      command: `${skill}.${command}`,
      error: err.message?.slice(0, 500) || 'Unknown error',
      duration: Date.now() - startTime,
    };
  }
}

// ============================================================
// MCP Server 初始化
// ============================================================

const server = new Server(
  {
    name: 'orchestrator-tools',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// ============================================================
// 列出所有 Tool
// ============================================================

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    // ============ Phase 1: 设计/规范 ============
    {
      name: 'scaffold_run',
      description: '运行官方脚手架工具生成可运行工程（基于 scaffold-runner）',
      inputSchema: {
        type: 'object',
        properties: {
          stack: {
            type: 'string',
            enum: ['react-vite', 'vue-vite', 'nextjs', 'nuxt', 'nest', 'spring-boot', 'fastapi', 'dotnet-webapi', 'rust', 'flutter', 'expo', 'python-lib'],
            description: '技术栈选择',
          },
          packageManager: {
            type: 'string',
            enum: ['npm', 'pnpm', 'yarn', 'cargo', 'uv'],
            default: 'pnpm',
          },
          projectName: { type: 'string', default: '.' },
          options: { type: 'object', additionalProperties: true },
        },
        required: ['stack'],
      },
    },

    {
      name: 'code_patterns_inject',
      description: '生成代码约定注入文本（基于 code-patterns）',
      inputSchema: {
        type: 'object',
        properties: {
          section: {
            type: 'string',
            enum: ['naming', 'error_handling', 'logging', 'api_calls', 'testing', 'comments', 'git', 'imports', 'file_structure', 'all'],
            default: 'all',
          },
          asFormat: { type: 'string', enum: ['prompt', 'yaml', 'markdown'], default: 'prompt' },
        },
      },
    },

    {
      name: 'ui_adjust',
      description: '聊天式 UI 调整：把模糊意图变为精确代码修改（基于 ui-design）',
      inputSchema: {
        type: 'object',
        properties: {
          instruction: { type: 'string', description: '自然语言指令，如"把首页卡片从 3 列改成 2 列"' },
          filePath: { type: 'string', description: '目标 HTML 文件路径（相对项目根）' },
          autoApply: { type: 'boolean', default: false, description: '是否自动应用（false = 只生成 diff 等用户确认）' },
        },
        required: ['instruction', 'filePath'],
      },
    },

    {
      name: 'design_generate',
      description: '从 User Story 自动生成 Page Flow + Page Detail + OpenAPI（基于 spec-userstory-to-design）',
      inputSchema: {
        type: 'object',
        properties: {
          featureName: { type: 'string' },
          specFile: { type: 'string', default: 'specs/001-feature/spec.md' },
          outputDir: { type: 'string' },
          format: {
            type: 'string',
            enum: ['mermaid-flowchart', 'mermaid-stateDiagram', 'mermaid-sequenceDiagram', 'all'],
            default: 'all',
          },
        },
        required: ['featureName'],
      },
    },

    {
      name: 'generate_openapi',
      description: '生成 OpenAPI 3.1.2 契约（含 RFC 9457 Problem + 双锚点；基于 api-contract）',
      inputSchema: {
        type: 'object',
        properties: {
          fromFiles: {
            type: 'array',
            items: { type: 'string' },
            description: '输入文件（plan.md / pages/*.md）',
          },
          outputPath: { type: 'string', default: 'contracts/openapi.yaml' },
          authType: { type: 'string', enum: ['jwt', 'oauth2', 'apiKey', 'none'], default: 'jwt' },
        },
        required: ['fromFiles'],
      },
    },

    {
      name: 'html_to_component',
      description: 'HTML 原型 → Vue 3 SFC / React TSX 组件（基于 html-converter）',
      inputSchema: {
        type: 'object',
        properties: {
          htmlFile: { type: 'string' },
          framework: { type: 'string', enum: ['vue3', 'react'], default: 'react' },
          typescript: { type: 'boolean', default: true },
          splitThreshold: { type: 'integer', default: 3, description: '重复结构 ≥N 次拆为子组件' },
          outputDir: { type: 'string', default: 'components' },
        },
        required: ['htmlFile', 'framework'],
      },
    },

    // ============ Phase 2: 变更管理 ============
    {
      name: 'openspec_propose',
      description: '创建 OpenSpec 变更提案（PROPOSAL.md，基于 openspec-workflow）',
      inputSchema: {
        type: 'object',
        properties: {
          changeName: { type: 'string', description: '如 "add-timesheet"' },
          intent: { type: 'string', description: '变更意图（自然语言）' },
          baseFeature: { type: 'string', default: 'main' },
        },
        required: ['changeName', 'intent'],
      },
    },

    // ============ Phase 3: 实施/质量 ============
    {
      name: 'implement_task',
      description: '按 tasks.md 单个任务执行（基于 implement-executor）',
      inputSchema: {
        type: 'object',
        properties: {
          taskId: { type: 'string', description: '如 "T015"' },
          featureId: { type: 'string', description: '如 "001-init"' },
          phase: { type: 'integer' },
          maxRetries: { type: 'integer', default: 3 },
          dryRun: { type: 'boolean', default: false, description: '只生成方案不实际改文件' },
        },
        required: ['taskId', 'featureId'],
      },
    },

    {
      name: 'run_tests',
      description: '运行测试 + 覆盖率 + 契约验证（基于 test-runner）',
      inputSchema: {
        type: 'object',
        properties: {
          phase: { type: 'string' },
          scope: { type: 'string', enum: ['all', 'unit', 'integration', 'contract', 'e2e'], default: 'all' },
          failOnCoverageBelow: { type: 'number', default: 80 },
          updateBaseline: { type: 'boolean', default: false, description: '是否更新覆盖率基线' },
        },
      },
    },

    {
      name: 'commit_with_changelog',
      description: '智能 commit（Conventional Commits + 自动推断 type/scope + 更新 CHANGELOG，基于 git-workflow）',
      inputSchema: {
        type: 'object',
        properties: {
          files: { type: 'array', items: { type: 'string' }, description: '要 add 的文件路径' },
          message: { type: 'string', description: 'commit message 主题' },
          taskId: { type: 'string' },
          storyId: { type: 'string' },
          signoff: { type: 'boolean', default: false, description: 'Co-authored-by 标记' },
        },
        required: ['files', 'message'],
      },
    },

    {
      name: 'create_pull_request',
      description: '创建 PR（自动填充模板 + 链接 spec/tasks/coverage，基于 git-workflow）',
      inputSchema: {
        type: 'object',
        properties: {
          feature: { type: 'string' },
          base: { type: 'string', default: 'main' },
          reviewers: { type: 'array', items: { type: 'string' } },
          labels: { type: 'array', items: { type: 'string' } },
          draft: { type: 'boolean', default: true },
        },
        required: ['feature'],
      },
    },

    {
      name: 'analyze_error',
      description: '错误分析（stack trace + 日志关联 + 根因定位 + 修复建议，基于 debug-helper）',
      inputSchema: {
        type: 'object',
        properties: {
          errorMessage: { type: 'string' },
          stackTrace: { type: 'string' },
          logFile: { type: 'string', description: '相关日志文件路径' },
          context: { type: 'object', additionalProperties: true },
        },
        required: ['errorMessage'],
      },
    },

    {
      name: 'review_pull_request',
      description: 'PR 评审（100+ 项检查，基于 review-checklist）',
      inputSchema: {
        type: 'object',
        properties: {
          prNumber: { type: 'integer' },
          base: { type: 'string', default: 'main' },
          strictMode: { type: 'boolean', default: true },
          categories: {
            type: 'array',
            items: { type: 'string', enum: ['BIZ', 'CONTRACT', 'SEC', 'PERF', 'MAINT', 'TEST'] },
            description: '要检查的类别（默认全部）',
          },
        },
        required: ['prNumber'],
      },
    },

    {
      name: 'audit_dependencies',
      description: '依赖审计（漏洞 + License + 维护活跃度 + Bundle Size，基于 dependency-auditor）',
      inputSchema: {
        type: 'object',
        properties: {
          addPackage: { type: 'string', description: '如 "axios@1.7"，可选（不传则审计整个项目）' },
          ecosystem: { type: 'string', enum: ['npm', 'pip', 'cargo', 'go'], default: 'npm' },
          failOnLicense: { type: 'array', items: { type: 'string' }, description: '禁止的 License（如 ["GPL-3.0"]）' },
        },
      },
    },

    {
      name: 'inject_secrets',
      description: '从 Doppler/Vault/.env 安全注入 Secrets 到进程环境（基于 environment-manager）',
      inputSchema: {
        type: 'object',
        properties: {
          env: { type: 'string', enum: ['dev', 'staging', 'production'], default: 'dev' },
          keys: { type: 'array', items: { type: 'string' }, description: '空 = 全部' },
          target: { type: 'string', enum: ['process', '.env.local', 'memory'], default: 'process' },
          backend: { type: 'string', enum: ['doppler', 'vault', 'dotenv'], default: 'doppler' },
        },
        required: ['env'],
      },
    },
  ],
}));

// ============================================================
// 执行 Tool：所有 15 个 Tool 真实调用对应 Skill CLI
// ============================================================

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  log(`Tool called: ${name}`);

  try {
    switch (name) {
      // ============ Phase 1: 设计/规范 ============
      case 'scaffold_run': {
        const result = await callSkill('scaffold-runner', 'run', {
          stack: args.stack,
          packageManager: args.packageManager ?? 'pnpm',
          projectName: args.projectName ?? '.',
          options: args.options ?? {},
        }, {
          timeoutMs: 180_000, // 脚手架可能较慢
        });
        return formatSkillResult(result);
      }

      case 'code_patterns_inject': {
        const result = await callSkill('code-patterns', 'inject', {
          section: args.section ?? 'all',
          asFormat: args.asFormat ?? 'prompt',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'ui_adjust': {
        const result = await callSkill('ui-design', 'adjust', {
          instruction: args.instruction,
          filePath: args.filePath,
          autoApply: args.autoApply ?? false,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'design_generate': {
        const result = await callSkill('spec-userstory-to-design', 'generate', {
          featureName: args.featureName,
          specFile: args.specFile,
          outputDir: args.outputDir,
          format: args.format ?? 'all',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'generate_openapi': {
        const result = await callSkill('api-contract', 'generate', {
          fromFiles: args.fromFiles,
          outputPath: args.outputPath ?? 'contracts/openapi.yaml',
          authType: args.authType ?? 'jwt',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'html_to_component': {
        const result = await callSkill('html-converter', 'convert', {
          htmlFile: args.htmlFile,
          framework: args.framework,
          typescript: args.typescript ?? true,
          splitThreshold: args.splitThreshold ?? 3,
          outputDir: args.outputDir ?? 'components',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      // ============ Phase 2: 变更管理 ============
      case 'openspec_propose': {
        const result = await callSkill('openspec-workflow', 'propose', {
          changeName: args.changeName,
          intent: args.intent,
          baseFeature: args.baseFeature ?? 'main',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      // ============ Phase 3: 实施/质量 ============
      case 'implement_task': {
        const result = await callSkill('implement-executor', 'implement', {
          taskId: args.taskId,
          featureId: args.featureId,
          phase: args.phase,
          maxRetries: args.maxRetries ?? 3,
          dryRun: args.dryRun ?? false,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 300_000, // 单任务可能 5 分钟
        });
        return formatSkillResult(result);
      }

      case 'run_tests': {
        const result = await callSkill('test-runner', 'run', {
          phase: args.phase,
          scope: args.scope ?? 'all',
          failOnCoverageBelow: args.failOnCoverageBelow ?? 80,
          updateBaseline: args.updateBaseline ?? false,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 240_000, // 测试可能较慢
        });
        return formatSkillResult(result);
      }

      case 'commit_with_changelog': {
        const result = await callSkill('git-workflow', 'commit', {
          files: args.files,
          message: args.message,
          taskId: args.taskId,
          storyId: args.storyId,
          signoff: args.signoff ?? false,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'create_pull_request': {
        const result = await callSkill('git-workflow', 'pr', {
          feature: args.feature,
          base: args.base ?? 'main',
          reviewers: args.reviewers ?? [],
          labels: args.labels ?? ['feature', 'auto-generated'],
          draft: args.draft ?? true,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'analyze_error': {
        const result = await callSkill('debug-helper', 'analyze', {
          errorMessage: args.errorMessage,
          stackTrace: args.stackTrace,
          logFile: args.logFile,
          context: args.context,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'review_pull_request': {
        const result = await callSkill('review-checklist', 'review', {
          prNumber: args.prNumber,
          base: args.base ?? 'main',
          strictMode: args.strictMode ?? true,
          categories: args.categories,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 180_000,
        });
        return formatSkillResult(result);
      }

      case 'audit_dependencies': {
        const result = await callSkill('dependency-auditor', 'audit', {
          addPackage: args.addPackage,
          ecosystem: args.ecosystem ?? 'npm',
          failOnLicense: args.failOnLicense ?? ['GPL-3.0', 'AGPL-3.0'],
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'inject_secrets': {
        const result = await callSkill('environment-manager', 'inject', {
          env: args.env,
          keys: args.keys ?? [],
          target: args.target ?? 'process',
          backend: args.backend ?? 'doppler',
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 30_000, // Secrets 注入要快（安全）
        });
        return formatSkillResult(result);
      }

      default:
        return {
          isError: true,
          content: [{ type: 'text', text: `Unknown tool: ${name}` }],
        };
    }
  } catch (error: any) {
    log(`Tool ${name} exception: ${error.message}`);
    return {
      isError: true,
      content: [{ type: 'text', text: `Tool ${name} failed: ${error.message}` }],
    };
  }
});

// ============================================================
// 格式化 Skill 返回结果为 MCP 响应
// ============================================================

function formatSkillResult(result: SkillResult) {
  // 成功：data 优先 + 摘要 + warnings
  if (result.ok && result.data) {
    const dataStr = JSON.stringify(result.data, null, 2);
    const warnings = result.warnings?.length
      ? `\n⚠️ Warnings:\n${result.warnings.map(w => `  - ${w}`).join('\n')}`
      : '';
    const next = result.nextActions?.length
      ? `\n📋 Next Actions:\n${result.nextActions.map(a => `  - ${a}`).join('\n')}`
      : '';
    const duration = result.duration ? ` (${result.duration}ms)` : '';
    const summary = result.data.summary || result.data.message || '';

    return {
      content: [{
        type: 'text',
        text: `✅ ${result.command}${duration}\n\n${summary}${warnings}${next}\n\n📦 Data:\n${dataStr}`,
      }],
    };
  }

  // 失败：错误信息
  return {
    isError: true,
    content: [{
      type: 'text',
      text: `❌ ${result.command}\n\nError: ${result.error || 'Unknown error'}`,
    }],
  };
}

// ============================================================
// 启动 Server
// ============================================================

const transport = new StdioServerTransport();
await server.connect(transport);

log(`orchestrator-tools MCP server started`);
log(`PROJECT_ROOT: ${PROJECT_ROOT}`);
log(`SKILL_BUNDLE_PATH: ${SKILL_BUNDLE_PATH}`);
log(`SKILL_CLI_BIN: ${SKILL_CLI_BIN}`);
log(`CLI exists: ${existsSync(SKILL_CLI_BIN)}`);