/**
 * 契约测试模板（test-runner.contract 自动生成示例）
 *
 * 本文件由 test-runner.contract 从 contracts/openapi.yaml 自动生成。
 * 每个 operationId 对应一个 describe 块，每个 describe 包含 3-5 个 it 用例。
 *
 * 设计原则：
 * 1. 每个端点至少覆盖：happy path + validation error + auth + rate limit + 边界
 * 2. 使用 toMatchSchema 校验响应 schema（自动从 openapi.yaml 推导）
 * 3. traceId 必出现在所有响应中（RFC 9457 合规）
 * 4. Idempotency-Key 在 mutating endpoints 自动使用
 *
 * @generated by project-orchestrator-bundle / test-runner
 * @date 2026-08-24
 * @openapi contracts/openapi.yaml
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// ============================================================
// 全局设置：加载 OpenAPI + 初始化 AJV
// ============================================================

const openapiPath = resolve(__dirname, '../../contracts/openapi.yaml');
let openapi: any;
let ajv: Ajv;

beforeAll(() => {
  openapi = YAML.load(readFileSync(openapiPath, 'utf-8'));
  ajv = addFormats(new Ajv({ strict: false, allErrors: true }));
});

// 辅助函数：从 openapi 路径读取 schema
const getSchema = (ref: string) => {
  const path = ref.replace('#/components/schemas/', '').split('/');
  let schema: any = openapi.components.schemas;
  for (const p of path) schema = schema[p];
  return schema;
};

// 辅助函数：从 openapi 路径读取 response
const getResponse = (ref: string) => {
  const path = ref.replace('#/components/responses/', '').split('/');
  let resp: any = openapi.components.responses;
  for (const p of path) resp = resp[p];
  return resp;
};

// 校验响应 schema
const validateSchema = (data: any, schema: any) => {
  const validate = ajv.compile(schema);
  const valid = validate(data);
  if (!valid) {
    throw new Error(`Schema validation failed: ${JSON.stringify(validate.errors, null, 2)}`);
  }
  return true;
};

// 校验 Problem schema（错误响应）
const validateProblem = (data: any) => {
  validateSchema(data, getSchema('Problem'));
  expect(data).toHaveProperty('traceId');
  expect(data.traceId).toBeTruthy();
};

// 测试客户端（mock fetch）
const apiClient = {
  baseURL: process.env.API_BASE || 'http://localhost:8080/v1',

  async request(path: string, options: any = {}) {
    const url = `${this.baseURL}${path}`;
    const res = await fetch(url, {
      method: options.method || 'GET',
      headers: {
        'Content-Type': 'application/json',
        ...(options.token && { Authorization: `Bearer ${options.token}` }),
        ...(options.headers || {}),
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });
    const data = res.status === 204 ? null : await res.json().catch(() => null);
    return { status: res.status, headers: res.headers, data };
  },
};

// ============================================================
// 1. POST /auth/login
// ============================================================
describe('POST /auth/login (openapi.yaml:paths./auth/login)', () => {
  it('should return:  200 + token + user on valid credentials', async () => {
    const res = await apiClient.request('/auth/login', {
      method: 'POST',
      body: { email: 'user@example.com', password: 'Password123', code: '123456' },
    });

    expect(res.status).toBe(200);
    expect(res.data).toHaveProperty('token');
    expect(res.data).toHaveProperty('user');
    validateSchema(res.data, getSchema('LoginResponse'));
  });

  it('should return:  400 on missing required fields', async () => {
    const res = await apiClient.request('/auth/login', {
      method: 'POST',
      body: { email: 'user@example.com' }, // missing password
    });

    expect(res.status).toBe(400);
    validateProblem(res.data);
    expect(res.data.code).toMatch(/^U1/); // 参数校验类错误
  });

  it('should return:  401 on invalid credentials', async () => {
    const res = await apiClient.request('/auth/login', {
      method: 'POST',
      body: { email: 'user@example.com', password: 'wrong-password' },
    });

    expect(res.status).toBe(401);
    validateProblem(res.data);
    expect(res.data.code).toBe('U1001'); // 凭据无效
  });

  it('should return:  422 on validation business rule violation', async () => {
    const res = await apiClient.request('/auth/login', {
      method: 'POST',
      body: { email: 'locked@example.com', password: 'Password123' },
    });

    expect(res.status).toBe(422);
    validateProblem(res.data);
    expect(res.data.code).toMatch(/^U2/); // 业务校验类
  });

  it('should return:  429 after 5 failed attempts within 10 minutes', async () => {
    // 5 次失败尝试
    for (let i = 0; i < 5; i++) {
      await apiClient.request('/auth/login', {
        method: 'POST',
        body: { email: 'user@example.com', password: 'wrong' },
      });
    }

    // 第 6 次应该被限流
    const res = await apiClient.request('/auth/login', {
      method: 'POST',
      body: { email: 'user@example.com', password: 'Password123' },
    });

    expect(res.status).toBe(429);
    expect(res.headers.get('retry-after')).toBeDefined();
    validateProblem(res.data);
  });

  it('should return:  500 on internal server error', async () => {
    // 模拟服务端崩溃（通过特殊 token 触发）
    const res = await apiClient.request('/auth/login', {
      method: 'POST',
      headers: { 'X-Test-Scenario': 'db-down' },
      body: { email: 'user@example.com', password: 'Password123' },
    });

    expect(res.status).toBe(500);
    validateProblem(res.data);
    expect(res.data.category).toBe('SYSTEM_ERROR');
    expect(res.data.traceId).toBeTruthy();
  });
});

// ============================================================
// 2. POST /auth/sms
// ============================================================
describe('POST /auth/sms (openapi.yaml:paths./auth/sms)', () => {
  it('should return:  200 + expiresIn on valid phone', async () => {
    const res = await apiClient.request('/auth/sms', {
      method: 'POST',
      body: { phone: '13800138000' },
    });

    expect(res.status).toBe(200);
    expect(res.data).toHaveProperty('expiresIn');
    expect(res.data.expiresIn).toBeGreaterThan(0);
  });

  it('should return:  400 on invalid phone format', async () => {
    const res = await apiClient.request('/auth/sms', {
      method: 'POST',
      body: { phone: '12345' }, // 不符合 11 位手机号
    });

    expect(res.status).toBe(400);
    validateProblem(res.data);
  });

  it('should return:  429 on rate limit (3 per minute)', async () => {
    // 短时间内连续发送
    for (let i = 0; i < 4; i++) {
      await apiClient.request('/auth/sms', {
        method: 'POST',
        body: { phone: '13800138000' },
      });
    }
    const res = await apiClient.request('/auth/sms', {
      method: 'POST',
      body: { phone: '13800138000' },
    });

    expect(res.status).toBe(429);
    expect(res.headers.get('retry-after')).toBeDefined();
  });
});

// ============================================================
// 3. POST /auth/oauth/douyin
// ============================================================
describe('POST /auth/oauth/douyin (openapi.yaml:paths./auth/oauth/douyin)', () => {
  it('should return:  200 + Account on valid OAuth code', async () => {
    const res = await apiClient.request('/auth/oauth/douyin', {
      method: 'POST',
      body: { code: 'valid_oauth_code_123', state: 'csrf_state_xyz' },
    });

    expect(res.status).toBe(200);
    validateSchema(res.data, getSchema('Account'));
    expect(res.data.platform).toBe('douyin');
  });

  it('should return:  401 on invalid OAuth code', async () => {
    const res = await apiClient.request('/auth/oauth/douyin', {
      method: 'POST',
      body: { code: 'invalid_code', state: 'csrf_state_xyz' },
    });

    expect(res.status).toBe(401);
    validateProblem(res.data);
  });

  it('should return:  409 when platform already linked', async () => {
    const res = await apiClient.request('/auth/oauth/douyin', {
      method: 'POST',
      headers: { 'X-Test-Scenario': 'already-linked' },
      body: { code: 'valid_code', state: 'csrf_state_xyz' },
    });

    expect(res.status).toBe(409);
    validateProblem(res.data);
    expect(res.data.code).toBe('U2003'); // 平台已接入
  });
});

// ============================================================
// 4. GET /accounts
// ============================================================
describe('GET /accounts (openapi.yaml:paths./accounts)', () => {
  it('should return:  200 + paginated accounts list', async () => {
    const res = await apiClient.request('/accounts', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    expect(res.data).toHaveProperty('items');
    expect(res.data).toHaveProperty('pagination');
    expect(Array.isArray(res.data.items)).toBe(true);
  });

  it('should return:  401 without bearer token', async () => {
    const res = await apiClient.request('/accounts');

    expect(res.status).toBe(401);
    validateProblem(res.data);
  });

  it('should support platform filter', async () => {
    const res = await apiClient.request('/accounts?platform=douyin', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    res.data.items.forEach((item: any) => {
      expect(item.platform).toBe('douyin');
    });
  });

  it('should support pagination params', async () => {
    const res = await apiClient.request('/accounts?page=0&pageSize=5', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    expect(res.data.items.length).toBeLessThanOrEqual(5);
  });
});

// ============================================================
// 5. POST /accounts/{id}/disable
// ============================================================
describe('POST /accounts/{id}/disable (openapi.yaml:paths./accounts/{id}/disable)', () => {
  it('should return:  200 + updated Account with status=disabled', async () => {
    const res = await apiClient.request('/accounts/acc-123/disable', {
      method: 'POST',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    validateSchema(res.data, getSchema('Account'));
    expect(res.data.status).toBe('disabled');
  });

  it('should return:  404 on non-existent account', async () => {
    const res = await apiClient.request('/accounts/non-existent-id/disable', {
      method: 'POST',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(404);
    validateProblem(res.data);
  });

  it('should return:  409 when account is already disabled', async () => {
    const res = await apiClient.request('/accounts/acc-disabled/disable', {
      method: 'POST',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(409);
    validateProblem(res.data);
  });
});

// ============================================================
// 6. DELETE /accounts/{id}
// ============================================================
describe('DELETE /accounts/{id} (openapi.yaml:paths./accounts/{id}.delete)', () => {
  it('should return:  204 on successful delete', async () => {
    const res = await apiClient.request('/accounts/acc-to-delete', {
      method: 'DELETE',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(204);
    expect(res.data).toBeNull();
  });

  it('should return:  404 when account not found', async () => {
    const res = await apiClient.request('/accounts/non-existent', {
      method: 'DELETE',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(404);
  });

  it('should return:  409 when account is still active', async () => {
    // 必须先 disable 才能删除
    const res = await apiClient.request('/accounts/acc-active', {
      method: 'DELETE',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(409);
    validateProblem(res.data);
  });
});

// ============================================================
// 7. POST /timesheets
// ============================================================
describe('POST /timesheets (openapi.yaml:paths./timesheets.post)', () => {
  it('should return:  201 + created Timesheet', async () => {
    const res = await apiClient.request('/timesheets', {
      method: 'POST',
      token: 'valid_jwt',
      body: {
        projectId: 'proj-123',
        date: '2026-08-24',
        hours: 4.5,
        description: '实现 JWT 鉴权',
      },
    });

    expect(res.status).toBe(201);
    validateSchema(res.data, getSchema('Timesheet'));
    expect(res.data).toHaveProperty('id');
    expect(res.data.createdAt).toBeDefined();
  });

  it('should return:  400 on invalid hours value', async () => {
    const res = await apiClient.request('/timesheets', {
      method: 'POST',
      token: 'valid_jwt',
      body: {
        projectId: 'proj-123',
        date: '2026-08-24',
        hours: 25, // 超过 24
      },
    });

    expect(res.status).toBe(400);
    validateProblem(res.data);
  });

  it('should return:  422 when project does not exist', async () => {
    const res = await apiClient.request('/timesheets', {
      method: 'POST',
      token: 'valid_jwt',
      body: {
        projectId: 'non-existent-project',
        date: '2026-08-24',
        hours: 2,
      },
    });

    expect(res.status).toBe(422);
    validateProblem(res.data);
    expect(res.data.code).toBe('U2004'); // 项目不存在
  });
});

// ============================================================
// 8. GET /timesheets
// ============================================================
describe('GET /timesheets (openapi.yaml:paths./timesheets.get)', () => {
  it('should return:  200 + paginated timesheets', async () => {
    const res = await apiClient.request('/timesheets', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    expect(Array.isArray(res.data.items)).toBe(true);
  });

  it('should filter by date range', async () => {
    const res = await apiClient.request(
      '/timesheets?startDate=2026-08-01&endDate=2026-08-31',
      { token: 'valid_jwt' }
    );

    expect(res.status).toBe(200);
    res.data.items.forEach((item: any) => {
      expect(item.date >= '2026-08-01').toBe(true);
      expect(item.date <= '2026-08-31').toBe(true);
    });
  });

  it('should return:  400 on invalid date format', async () => {
    const res = await apiClient.request('/timesheets?startDate=invalid', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(400);
    validateProblem(res.data);
  });
});

// ============================================================
// 9. GET /projects
// ============================================================
describe('GET /projects (openapi.yaml:paths./projects.get)', () => {
  it('should return:  200 + paginated projects', async () => {
    const res = await apiClient.request('/projects', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    expect(Array.isArray(res.data.items)).toBe(true);
  });

  it('should filter by status=archived', async () => {
    const res = await apiClient.request('/projects?status=archived', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    res.data.items.forEach((item: any) => {
      expect(item.status).toBe('archived');
    });
  });

  it('should default to status=active when no status param', async () => {
    const res = await apiClient.request('/projects', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    res.data.items.forEach((item: any) => {
      expect(item.status).toBe('active');
    });
  });
});

// ============================================================
// 10. POST /projects
// ============================================================
describe('POST /projects (openapi.yaml:paths./projects.post)', () => {
  it('should return:  201 + created Project', async () => {
    const res = await apiClient.request('/projects', {
      method: 'POST',
      token: 'valid_jwt',
      body: {
        name: '客服系统',
        description: 'AI 驱动的多平台客服系统',
      },
    });

    expect(res.status).toBe(201);
    validateSchema(res.data, getSchema('Project'));
  });

  it('should return:  400 on empty name', async () => {
    const res = await apiClient.request('/projects', {
      method: 'POST',
      token: 'valid_jwt',
      body: { name: '' },
    });

    expect(res.status).toBe(400);
    validateProblem(res.data);
  });

  it('should return:  409 when project name already exists', async () => {
    const res = await apiClient.request('/projects', {
      method: 'POST',
      token: 'valid_jwt',
      headers: { 'X-Test-Scenario': 'duplicate-name' },
      body: { name: '客服系统' },
    });

    expect(res.status).toBe(409);
    validateProblem(res.data);
  });
});

// ============================================================
// 11. GET /boards/{id}
// ============================================================
describe('GET /boards/{id} (openapi.yaml:paths./boards/{id})', () => {
  it('should return:  200 + Board with columns', async () => {
    const res = await apiClient.request('/boards/board-123', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    validateSchema(res.data, getSchema('Board'));
    expect(Array.isArray(res.data.columns)).toBe(true);
  });

  it('should return:  404 on non-existent board', async () => {
    const res = await apiClient.request('/boards/non-existent', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(404);
    validateProblem(res.data);
  });
});

// ============================================================
// 12. POST /boards/{id}/cards
// ============================================================
describe('POST /boards/{id}/cards (openapi.yaml:paths./boards/{id}/cards)', () => {
  it('should return:  201 + created Card', async () => {
    const res = await apiClient.request('/boards/board-123/cards', {
      method: 'POST',
      token: 'valid_jwt',
      body: {
        columnId: 'col-todo',
        title: '实现 OAuth 接入',
        description: '接入抖音 OAuth',
      },
    });

    expect(res.status).toBe(201);
    validateSchema(res.data, getSchema('Card'));
  });

  it('should return:  404 when board does not exist', async () => {
    const res = await apiClient.request('/boards/non-existent/cards', {
      method: 'POST',
      token: 'valid_jwt',
      body: { columnId: 'col-1', title: '任务' },
    });

    expect(res.status).toBe(404);
  });
});

// ============================================================
// 13. PATCH /cards/{id}
// ============================================================
describe('PATCH /cards/{id} (openapi.yaml:paths./cards/{id}.patch)', () => {
  it('should return:  200 + updated Card', async () => {
    const res = await apiClient.request('/cards/card-123', {
      method: 'PATCH',
      token: 'valid_jwt',
      body: {
        title: '已更新：实现 OAuth 接入',
        assigneeId: 'user-456',
        dueDate: '2026-08-30',
      },
    });

    expect(res.status).toBe(200);
    validateSchema(res.data, getSchema('Card'));
  });

  it('should return:  400 on invalid date format', async () => {
    const res = await apiClient.request('/cards/card-123', {
      method: 'PATCH',
      token: 'valid_jwt',
      body: { dueDate: 'invalid-date' },
    });

    expect(res.status).toBe(400);
    validateProblem(res.data);
  });

  it('should return:  404 when card not found', async () => {
    const res = await apiClient.request('/cards/non-existent', {
      method: 'PATCH',
      token: 'valid_jwt',
      body: { title: '更新' },
    });

    expect(res.status).toBe(404);
  });
});

// ============================================================
// 14. DELETE /cards/{id}
// ============================================================
describe('DELETE /cards/{id} (openapi.yaml:paths./cards/{id}.delete)', () => {
  it('should return:  204 on successful delete', async () => {
    const res = await apiClient.request('/cards/card-123', {
      method: 'DELETE',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(204);
  });

  it('should return:  409 when card has dependencies', async () => {
    const res = await apiClient.request('/cards/card-with-deps', {
      method: 'DELETE',
      token: 'valid_jwt',
    });

    expect(res.status).toBe(409);
    validateProblem(res.data);
  });
});

// ============================================================
// 15. GET /notifications
// ============================================================
describe('GET /notifications (openapi.yaml:paths./notifications)', () => {
  it('should return:  200 + paginated notifications', async () => {
    const res = await apiClient.request('/notifications', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    expect(Array.isArray(res.data.items)).toBe(true);
  });

  it('should support unreadOnly filter', async () => {
    const res = await apiClient.request('/notifications?unreadOnly=true', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
    res.data.items.forEach((item: any) => {
      expect(item.read).toBe(false);
    });
  });
});

// ============================================================
// 16. POST /uploads
// ============================================================
describe('POST /uploads (openapi.yaml:paths./uploads)', () => {
  it('should return:  201 + UploadResult with URL', async () => {
    const formData = new FormData();
    const blob = new Blob(['fake-image-bytes'], { type: 'image/png' });
    formData.append('file', blob, 'avatar.png');
    formData.append('category', 'avatar');

    const res = await fetch(`${apiClient.baseURL}/uploads`, {
      method: 'POST',
      headers: { Authorization: 'Bearer valid_jwt' },
      body: formData,
    });

    expect(res.status).toBe(201);
    const data = await res.json();
    expect(data).toHaveProperty('id');
    expect(data).toHaveProperty('url');
    expect(data.url).toMatch(/^https:\/\//);
  });

  it('should return:  400 when file is missing', async () => {
    const formData = new FormData();
    formData.append('category', 'avatar');

    const res = await fetch(`${apiClient.baseURL}/uploads`, {
      method: 'POST',
      headers: { Authorization: 'Bearer valid_jwt' },
      body: formData,
    });

    expect(res.status).toBe(400);
  });

  it('should return:  413 when file exceeds size limit', async () => {
    // 创建超大文件（mock）
    const formData = new FormData();
    const bigBlob = new Blob([new ArrayBuffer(20 * 1024 * 1024)], { type: 'image/png' });
    formData.append('file', bigBlob, 'huge.png');
    formData.append('category', 'avatar');

    const res = await fetch(`${apiClient.baseURL}/uploads`, {
      method: 'POST',
      headers: { Authorization: 'Bearer valid_jwt' },
      body: formData,
    });

    expect(res.status).toBe(413);
  });
});

// ============================================================
// 17. GET /reports/weekly
// ============================================================
describe('GET /reports/weekly (openapi.yaml:paths./reports/weekly)', () => {
  it('should return:  200 + WeeklyReport with project breakdown', async () => {
    const res = await apiClient.request(
      '/reports/weekly?weekStart=2026-08-19',
      { token: 'valid_jwt' }
    );

    expect(res.status).toBe(200);
    validateSchema(res.data, getSchema('WeeklyReport'));
    expect(res.data).toHaveProperty('totalHours');
    expect(Array.isArray(res.data.projectBreakdown)).toBe(true);
  });

  it('should default to current week when no weekStart', async () => {
    const res = await apiClient.request('/reports/weekly', {
      token: 'valid_jwt',
    });

    expect(res.status).toBe(200);
  });
});

// ============================================================
// 18. POST /webhooks/douyin
// ============================================================
describe('POST /webhooks/douyin (openapi.yaml:paths./webhooks/douyin)', () => {
  it('should return:  200 on valid webhook with signature', async () => {
    const res = await fetch(`${apiClient.baseURL}/webhooks/douyin`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Douyin-Signature': 'valid_hmac_signature_abc',
      },
      body: JSON.stringify({
        event: 'message.received',
        timestamp: 1692864000,
        data: { messageId: 'msg-123', content: '你好' },
      }),
    });

    expect(res.status).toBe(200);
  });

  it('should return:  401 on invalid signature', async () => {
    const res = await fetch(`${apiClient.baseURL}/webhooks/douyin`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Douyin-Signature': 'invalid_signature',
      },
      body: JSON.stringify({ event: 'message.received', timestamp: 1692864000, data: {} }),
    });

    expect(res.status).toBe(401);
  });
});

// ============================================================
// 契约覆盖率自动验证（test-runner.contract 自动生成的元测试）
// ============================================================
describe('Contract Coverage Meta-Test', () => {
  it('should cover all operations defined in openapi.yaml', () => {
    const paths = openapi.paths || {};
    const operationIds = Object.values(paths)
      .flatMap((path: any) => Object.values(path).filter((op: any) => op.operationId).map((op: any) => op.operationId));

    // 这里列出所有 operationId，必须每个都被覆盖
    const expectedOperations = [
      'login', 'sendSmsCode', 'douyinOAuth',
      'listAccounts', 'disableAccount', 'deleteAccount',
      'createTimesheet', 'listTimesheets',
      'listProjects', 'createProject',
      'getBoard', 'createCard',
      'updateCard', 'deleteCard',
      'listNotifications',
      'uploadFile',
      'getWeeklyReport',
      'douyinWebhook',
    ];

    operationIds.sort();
    expectedOperations.sort();

    expect(operationIds).toEqual(expectedOperations);
  });

  it('should have traceId in all response schemas', () => {
    const problemSchema = getSchema('Problem');
    expect(problemSchema.required).toContain('traceId');
    expect(problemSchema.properties.traceId).toBeDefined();
  });

  it('should have security defined for protected operations', () => {
    const protectedPaths = Object.entries(openapi.paths)
      .filter(([path, ops]: [string, any]) => path !== '/auth/login' && path !== '/auth/sms');

    protectedPaths.forEach(([path, ops]: [string, any]) => {
      Object.values(ops).forEach((op: any) => {
        if (op.operationId) {
          expect(op.security || openapi.security, `${path} should have security`).toBeDefined();
        }
      });
    });
  });
});