/**
 * orchestrator-tools MCP Server
 *
 * 把 project-orchestrator-bundle 的 15 个子 Skill 的核心入口封装为 MCP Tool。
 * 让 Skills 可以被任何 MCP Host（Trae / Claude Code / Cursor / VS Code）调用。
 *
 * 协议：MCP 2026-07-28（无状态核心 + sampling）
 * 传输：stdio（推荐）或 Streamable HTTP
 *
 * 关键设计：
 * 1. 每个 Tool 通过 fork() 子进程调用对应 Skill 的 CLI（统一接口 + IPC）
 * 2. Skill 需要调用 LLM 时，通过 IPC 向 MCP Server 发送 llm:request
 * 3. MCP Server 通过 sampling/createMessage 向 TRAE Client 请求 LLM 推理
 * 4. TRAE 使用自身 Agent 框架的 LLM 完成推理，结果经 IPC 回传给 Skill
 *
 * @generated by project-orchestrator-bundle / mcp-integration
 * @date 2026-08-25
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  CreateMessageRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { fork } from 'child_process';
import { existsSync } from 'fs';
import { resolve } from 'path';

// ============================================================
// 环境配置
// ============================================================

const PROJECT_ROOT = process.env.PROJECT_ROOT || process.cwd();
const SKILL_BUNDLE_PATH = process.env.SKILL_BUNDLE_PATH || PROJECT_ROOT;
const SKILL_CLI_BIN = process.env.SKILL_CLI_BIN ||
  resolve(SKILL_BUNDLE_PATH, 'mcp-integration/dist/skill-cli.cjs');

const DEFAULT_TIMEOUT_MS = 120_000;

const log = (msg: string) => console.error(`[orchestrator-tools] ${msg}`);

// ============================================================
// 类型定义
// ============================================================

interface SkillResult<T = any> {
  ok: boolean;
  command: string;
  data?: T;
  error?: string;
  warnings?: string[];
  nextActions?: string[];
  duration?: number;
}

interface LLMRequest {
  type: 'llm:request';
  id: number;
  system?: string;
  messages: Array<{ role: string; content: string }>;
  maxTokens?: number;
  temperature?: number;
}

interface LLMResponse {
  type: 'llm:response';
  id: number;
  ok: boolean;
  content?: string;
  model?: string;
  error?: string;
}

// ============================================================
// MCP Sampling：通过 IPC 转发 Skill 的 LLM 请求到 TRAE Client
// ============================================================

/**
 * 延迟检测 Client 是否支持 sampling。
 * 注意：不能在 server.connect() 后立即检测，因为 initialize 握手还未完成。
 * 在实际处理 LLM 请求时动态检测并缓存结果。
 */
let _samplingChecked = false;
let _samplingEnabled = false;

function isSamplingEnabled(): boolean {
  if (!_samplingChecked) {
    try {
      const clientCapabilities = (server as any).getClientCapabilities?.() || {};
      _samplingEnabled = !!clientCapabilities?.sampling;
    } catch {
      _samplingEnabled = false;
    }
    _samplingChecked = true;
    log(`Client sampling support: ${_samplingEnabled ? 'YES' : 'NO'}`);
  }
  return _samplingEnabled;
}

async function handleLLMRequest(
  child: any,
  request: LLMRequest
): Promise<void> {
  const msgId = request.id;
  log(`LLM request #${msgId}: ${request.messages.length} messages, maxTokens=${request.maxTokens}`);

  if (!isSamplingEnabled()) {
    child.send({
      type: 'llm:response',
      id: msgId,
      ok: false,
      error: 'MCP sampling not available (client does not support sampling)',
    } as LLMResponse);
    return;
  }

  try {
    const result = await server.request(
      {
        method: 'sampling/createMessage',
        params: {
          messages: request.messages.map(m => ({
            role: m.role as 'user' | 'assistant',
            content: { type: 'text' as const, text: m.content },
          })),
          systemPrompt: request.system || undefined,
          temperature: request.temperature,
          maxTokens: request.maxTokens || 4096,
        },
      },
      CreateMessageRequestSchema as any,
    );

    const text = (result as any)?.content?.text || '';
    const model = (result as any)?.model || 'unknown';

    child.send({
      type: 'llm:response',
      id: msgId,
      ok: true,
      content: text,
      model,
    } as LLMResponse);

    log(`LLM response #${msgId}: ${text.length} chars from ${model}`);
  } catch (err: any) {
    log(`LLM request #${msgId} FAILED: ${err.message}`);
    child.send({
      type: 'llm:response',
      id: msgId,
      ok: false,
      error: err.message?.slice(0, 500) || 'MCP sampling failed',
    } as LLMResponse);
  }
}

// ============================================================
// 调用 Skill CLI（使用 fork + IPC 替代 exec）
// ============================================================

async function callSkill(
  skill: string,
  command: string,
  input: Record<string, any>,
  options: { timeoutMs?: number; cwd?: string } = {}
): Promise<SkillResult> {
  const startTime = Date.now();
  const timeout = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const cwd = options.cwd ?? PROJECT_ROOT;

  if (!existsSync(SKILL_CLI_BIN)) {
    return {
      ok: false,
      command: `${skill}.${command}`,
      error: `Skill CLI not found at ${SKILL_CLI_BIN}. ` +
        `Build it first: cd ${SKILL_BUNDLE_PATH} && pnpm build`,
    };
  }

  // 通过 stdin 传递 input JSON（避免命令行长度限制 + PowerShell 解析问题）
  const inputJson = JSON.stringify(input);
  const args = [skill, command, '--project-root', cwd];

  return new Promise((resolvePromise) => {
    let stdout = '';
    let stderr = '';
    let resolved = false;

    const child = fork(SKILL_CLI_BIN, args, {
      cwd: PROJECT_ROOT,
      stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
      env: {
        ...process.env,
        // 始终开启 MCP sampling 尝试（子进程会自动检测，失败则降级）
        MCP_SAMPLING_ENABLED: '1',
        // 告诉 skill-cli 从 stdin 读取 input（避免命令行长度限制 + PowerShell 解析问题）
        SKILL_INPUT_FROM_STDIN: '1',
      },
    });

    // 将 input JSON 写入子进程 stdin
    child.stdin?.write(inputJson);
    child.stdin?.end();

    // 收集 stdout / stderr
    child.stdout?.on('data', (data: Buffer) => { stdout += data.toString(); });
    child.stderr?.on('data', (data: Buffer) => { stderr += data.toString(); });

    // 处理来自子进程的 IPC 消息（LLM 请求）
    child.on('message', (msg: any) => {
      if (msg?.type === 'llm:request') {
        handleLLMRequest(child, msg as LLMRequest).catch((err) => {
          log(`LLM handler error: ${err.message}`);
        });
      }
    });

    // 超时处理
    const timer = setTimeout(() => {
      if (!resolved) {
        child.kill('SIGTERM');
        setTimeout(() => {
          if (!resolved) child.kill('SIGKILL');
        }, 5000);
        resolvePromise({
          ok: false,
          command: `${skill}.${command}`,
          error: `Timeout after ${timeout}ms`,
          duration: Date.now() - startTime,
        });
        resolved = true;
      }
    }, timeout);

    // 子进程退出
    child.on('close', (code: number) => {
      clearTimeout(timer);
      if (resolved) return;

      if (stderr) {
        log(`[${skill}.${command}] stderr: ${stderr.slice(0, 500)}`);
      }

      try {
        const result: SkillResult = JSON.parse(stdout);
        result.duration = Date.now() - startTime;
        resolvePromise(result);
      } catch {
        // stdout 不是 JSON
        resolvePromise({
          ok: false,
          command: `${skill}.${command}`,
          error: code !== 0
            ? `Process exited with code ${code}. stdout: ${stdout.slice(0, 200)}`
            : `Failed to parse output: ${stdout.slice(0, 200)}`,
          duration: Date.now() - startTime,
        });
      }
      resolved = true;
    });

    // 子进程错误
    child.on('error', (err: Error) => {
      clearTimeout(timer);
      if (resolved) return;
      log(`[${skill}.${command}] fork error: ${err.message}`);
      resolvePromise({
        ok: false,
        command: `${skill}.${command}`,
        error: err.message,
        duration: Date.now() - startTime,
      });
      resolved = true;
    });
  });
}

// ============================================================
// MCP Server 初始化（注册 sampling capability）
// ============================================================

const server = new Server(
  {
    name: 'orchestrator-tools',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
      sampling: {},
    },
  }
);

// ============================================================
// 列出所有 Tool
// ============================================================

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    // ============ Phase 1: 项目初始化 ============
    {
      name: 'spec_bootstrap_constitution',
      description: 'spec-bootstrap.constitution — 建立项目宪法（治理原则 + 质量红线 + 技术规范）',
      inputSchema: {
        type: 'object',
        properties: {
          projectName: { type: 'string', default: 'NewProject', description: '项目名称' },
          principles: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                description: { type: 'string' },
              },
              required: ['name'],
            },
            description: '核心原则列表，覆盖默认模板',
          },
        },
      },
    },

    {
      name: 'spec_bootstrap_specify',
      description: 'spec-bootstrap.specify — 从需求描述生成首个 feature 的 spec.md',
      inputSchema: {
        type: 'object',
        properties: {
          description: { type: 'string', description: '功能需求描述（自然语言）' },
        },
        required: ['description'],
      },
    },

    {
      name: 'spec_bootstrap_clarify',
      description: 'spec-bootstrap.clarify — 扫描 spec.md 中的歧义点，最多列出 5 个待澄清问题',
      inputSchema: {
        type: 'object',
        properties: {
          specFile: { type: 'string', default: 'specs/001-feature/spec.md', description: 'spec.md 路径（相对项目根）' },
        },
      },
    },

    {
      name: 'spec_bootstrap_plan',
      description: 'spec-bootstrap.plan — 基于 spec.md 生成技术方案 plan.md（架构 + 模块 + 数据流）',
      inputSchema: {
        type: 'object',
        properties: {
          specFile: { type: 'string', default: 'specs/001-feature/spec.md', description: 'spec.md 路径（相对项目根）' },
        },
      },
    },

    {
      name: 'spec_bootstrap_checklist',
      description: 'spec-bootstrap.checklist — 生成领域质量检查清单（质量门）',
      inputSchema: {
        type: 'object',
        properties: {
          specFile: { type: 'string', default: 'specs/001-feature/spec.md', description: 'spec.md 路径（相对项目根）' },
        },
      },
    },

    {
      name: 'spec_bootstrap_tasks',
      description: 'spec-bootstrap.tasks — 基于 plan.md 拆分为可执行任务列表 tasks.md',
      inputSchema: {
        type: 'object',
        properties: {
          planFile: { type: 'string', default: 'specs/001-feature/plan.md', description: 'plan.md 路径（相对项目根）' },
        },
      },
    },

    {
      name: 'spec_bootstrap_analyze',
      description: 'spec-bootstrap.analyze — 一致性扫描：检查 spec/plan/tasks 三者是否一致',
      inputSchema: {
        type: 'object',
        properties: {
          feature: { type: 'string', default: '001-feature', description: 'feature 目录名' },
        },
      },
    },

    {
      name: 'spec_bootstrap_implement',
      description: 'spec-bootstrap.implement — 启动实现（调度到 implement-executor）',
      inputSchema: {
        type: 'object',
        properties: {
          taskId: { type: 'string', description: '任务 ID，如 T001' },
          phase: { type: 'integer', description: 'Phase 编号' },
        },
        required: ['taskId'],
      },
    },

    {
      name: 'scaffold_runner_run',
      description: 'scaffold-runner.run — 脚手架生成（17 种技术栈）',
      inputSchema: {
        type: 'object',
        properties: {
          stack: {
            type: 'string',
            enum: ['react-vite', 'vue3-vite', 'next-app', 'nuxt-app', 'flutter-app', 'express-api', 'nestjs-api', 'koa-api', 'spring-boot', 'fastapi', 'go-api', 'rust-api', 'django-api', 'dotnet-api', 'ts-lib', 'node-cli', 'vitest-starter'],
            description: '技术栈选择',
          },
          packageManager: {
            type: 'string',
            enum: ['npm', 'pnpm', 'yarn', 'cargo', 'uv'],
            default: 'pnpm',
          },
          projectName: { type: 'string', default: '.' },
          options: { type: 'object', additionalProperties: true },
        },
        required: ['stack'],
      },
    },

    {
      name: 'code_patterns_generate',
      description: 'code-patterns.generate — 生成代码规范模式（22 种设计模式）',
      inputSchema: {
        type: 'object',
        properties: {
          section: {
            type: 'string',
            enum: ['naming', 'error_handling', 'logging', 'api_calls', 'testing', 'comments', 'git', 'imports', 'file_structure', 'all'],
            default: 'all',
          },
          asFormat: { type: 'string', enum: ['prompt', 'yaml', 'markdown'], default: 'prompt' },
        },
      },
    },

    {
      name: 'ui_design_adjust',
      description: 'ui-design.adjust — 聊天式 UI 调整（模糊意图 → 精确代码修改）',
      inputSchema: {
        type: 'object',
        properties: {
          instruction: { type: 'string', description: '自然语言指令，如"把首页卡片从 3 列改成 2 列"' },
          filePath: { type: 'string', description: '目标 HTML 文件路径（相对项目根）' },
          autoApply: { type: 'boolean', default: false, description: '是否自动应用（false = 只生成 diff 等用户确认）' },
        },
        required: ['instruction', 'filePath'],
      },
    },

    {
      name: 'spec_userstory_to_design_generate',
      description: 'spec-userstory-to-design.generate — User Story → Page Flow + Page Detail + OpenAPI',
      inputSchema: {
        type: 'object',
        properties: {
          featureName: { type: 'string' },
          specFile: { type: 'string', default: 'specs/001-feature/spec.md' },
          outputDir: { type: 'string' },
          format: {
            type: 'string',
            enum: ['mermaid-flowchart', 'mermaid-stateDiagram', 'mermaid-sequenceDiagram', 'all'],
            default: 'all',
          },
        },
        required: ['featureName'],
      },
    },

    {
      name: 'api_contract_generate',
      description: 'api-contract.generate — 生成 OpenAPI 3.1.2 契约（含 RFC 9457 Problem + Bearer JWT）',
      inputSchema: {
        type: 'object',
        properties: {
          fromFiles: {
            type: 'array',
            items: { type: 'string' },
            description: '输入文件（plan.md / pages/*.md）',
          },
          outputPath: { type: 'string', default: 'contracts/openapi.yaml' },
          authType: { type: 'string', enum: ['jwt', 'oauth2', 'apiKey', 'none'], default: 'jwt' },
        },
        required: ['fromFiles'],
      },
    },

    {
      name: 'html_converter_convert',
      description: 'html-converter.convert — HTML 原型 → Vue 3 SFC / React TSX 组件',
      inputSchema: {
        type: 'object',
        properties: {
          htmlFile: { type: 'string' },
          framework: { type: 'string', enum: ['vue3', 'react'], default: 'react' },
          typescript: { type: 'boolean', default: true },
          splitThreshold: { type: 'integer', default: 3, description: '重复结构 ≥N 次拆为子组件' },
          outputDir: { type: 'string', default: 'components' },
        },
        required: ['htmlFile', 'framework'],
      },
    },

    // ============ Phase 2: 功能变更与实现 ============
    {
      name: 'openspec_workflow_propose',
      description: 'openspec-workflow.propose — 创建变更提案（PROPOSAL.md）',
      inputSchema: {
        type: 'object',
        properties: {
          changeName: { type: 'string', description: '如 "add-timesheet"' },
          intent: { type: 'string', description: '变更意图（自然语言）' },
          baseFeature: { type: 'string', default: 'main' },
        },
        required: ['changeName', 'intent'],
      },
    },

    {
      name: 'implement_executor_run',
      description: 'implement-executor.run — Phase 驱动 LLM Agent 代码生成（任务拆解 + 编码 + 自检 + Checkpoint）',
      inputSchema: {
        type: 'object',
        properties: {
          taskId: { type: 'string', description: '如 "T015"' },
          featureId: { type: 'string', description: '如 "001-init"' },
          phase: { type: 'integer' },
          maxRetries: { type: 'integer', default: 3 },
          dryRun: { type: 'boolean', default: false, description: '只生成方案不实际改文件' },
        },
        required: ['taskId', 'featureId'],
      },
    },

    {
      name: 'implement_executor_resume',
      description: 'implement-executor.resume — 断点恢复：从上次暂停/中断的状态继续执行（支持跳过失败任务）',
      inputSchema: {
        type: 'object',
        properties: {
          featureId: { type: 'string', description: '如 "001-init"' },
          skipFailedTasks: { type: 'boolean', default: false, description: '跳过当前失败的任务，继续执行后续任务' },
          fromPhase: { type: 'integer', description: '从指定 Phase 开始执行（跳过之前的 Phase）' },
        },
      },
    },

    {
      name: 'implement_executor_status',
      description: 'implement-executor.status — 查看任务进度 + 断点恢复状态（暂停/失败/跳过/重试预算）',
      inputSchema: {
        type: 'object',
        properties: {
          featureId: { type: 'string', description: '如 "001-init"' },
        },
      },
    },

    {
      name: 'implement_executor_rollback',
      description: 'implement-executor.rollback — 回滚到 pre-run git HEAD 并清理状态文件（git reset --hard）',
      inputSchema: {
        type: 'object',
        properties: {
          featureId: { type: 'string', description: '如 "001-init"' },
          toHead: { type: 'string', description: '指定回滚目标 commit hash（不指定则使用 originalGitHead）' },
        },
      },
    },

    {
      name: 'test_runner_run',
      description: 'test-runner.run — 运行测试 + 覆盖率 + 契约验证',
      inputSchema: {
        type: 'object',
        properties: {
          phase: { type: 'string' },
          scope: { type: 'string', enum: ['all', 'unit', 'integration', 'contract', 'e2e'], default: 'all' },
          failOnCoverageBelow: { type: 'number', default: 80 },
          updateBaseline: { type: 'boolean', default: false, description: '是否更新覆盖率基线' },
        },
      },
    },

    {
      name: 'git_workflow_commit',
      description: 'git-workflow.commit — 智能提交（Conventional Commits + 自动推断 type/scope）',
      inputSchema: {
        type: 'object',
        properties: {
          files: { type: 'array', items: { type: 'string' }, description: '要 add 的文件路径' },
          message: { type: 'string', description: 'commit message 主题' },
          taskId: { type: 'string' },
          storyId: { type: 'string' },
          signoff: { type: 'boolean', default: false, description: 'Co-authored-by 标记' },
        },
        required: ['files', 'message'],
      },
    },

    {
      name: 'git_workflow_pr',
      description: 'git-workflow.pr — 创建 PR（自动填充模板 + 链接 spec/tasks/coverage）',
      inputSchema: {
        type: 'object',
        properties: {
          feature: { type: 'string' },
          base: { type: 'string', default: 'main' },
          reviewers: { type: 'array', items: { type: 'string' } },
          labels: { type: 'array', items: { type: 'string' } },
          draft: { type: 'boolean', default: true },
        },
        required: ['feature'],
      },
    },

    // ============ Phase 3: 质量保障 ============
    {
      name: 'debug_helper_analyze',
      description: 'debug-helper.analyze — 错误分析（stack trace + 日志关联 + 三层根因 + 修复建议）',
      inputSchema: {
        type: 'object',
        properties: {
          errorMessage: { type: 'string' },
          stackTrace: { type: 'string' },
          logFile: { type: 'string', description: '相关日志文件路径' },
          context: { type: 'object', additionalProperties: true },
        },
        required: ['errorMessage'],
      },
    },

    {
      name: 'review_checklist_review',
      description: 'review-checklist.review — PR 评审（7 大类 73 条规则：BIZ + CONTRACT + SEC + PERF + MAINT + TEST + PATTERN）',
      inputSchema: {
        type: 'object',
        properties: {
          prNumber: { type: 'integer' },
          base: { type: 'string', default: 'main' },
          strictMode: { type: 'boolean', default: true },
          categories: {
            type: 'array',
            items: { type: 'string', enum: ['BIZ', 'CONTRACT', 'SEC', 'PERF', 'MAINT', 'TEST', 'PATTERN'] },
            description: '要检查的类别（默认全部）',
          },
        },
        required: ['prNumber'],
      },
    },

    {
      name: 'dependency_auditor_audit',
      description: 'dependency-auditor.audit — 依赖审计（真实 npm audit + License 合规 + 健康度评分）',
      inputSchema: {
        type: 'object',
        properties: {
          addPackage: { type: 'string', description: '如 "axios@1.7"，可选（不传则审计整个项目）' },
          ecosystem: { type: 'string', enum: ['npm', 'pip', 'cargo', 'go'], default: 'npm' },
          failOnLicense: { type: 'array', items: { type: 'string' }, description: '禁止的 License（如 ["GPL-3.0"]）' },
        },
      },
    },

    {
      name: 'environment_manager_inject',
      description: 'environment-manager.inject — 环境配置注入（4 环境 + Secrets 安全注入）',
      inputSchema: {
        type: 'object',
        properties: {
          env: { type: 'string', enum: ['dev', 'test', 'staging', 'prod'], default: 'dev' },
          keys: { type: 'array', items: { type: 'string' }, description: '空 = 全部' },
          target: { type: 'string', enum: ['process', '.env.local', 'memory'], default: 'process' },
          backend: { type: 'string', enum: ['doppler', 'vault', 'dotenv'], default: 'dotenv' },
        },
        required: ['env'],
      },
    },
  ],
}));

// ============================================================
// 执行 Tool：所有 15 个 Tool 真实调用对应 Skill CLI
// ============================================================

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} as Record<string, any> } = request.params;
  log(`Tool called: ${name}`);

  try {
    switch (name) {
      // ============ Phase 1: 项目初始化 ============
      case 'spec_bootstrap_constitution': {
        const result = await callSkill('spec-bootstrap', 'constitution', {
          projectName: args.projectName ?? 'NewProject',
          principles: args.principles ?? [],
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_specify': {
        const result = await callSkill('spec-bootstrap', 'specify', {
          description: args.description,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_clarify': {
        const result = await callSkill('spec-bootstrap', 'clarify', {
          specFile: args.specFile ?? 'specs/001-feature/spec.md',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_plan': {
        const result = await callSkill('spec-bootstrap', 'plan', {
          specFile: args.specFile ?? 'specs/001-feature/spec.md',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_checklist': {
        const result = await callSkill('spec-bootstrap', 'checklist', {
          specFile: args.specFile ?? 'specs/001-feature/spec.md',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_tasks': {
        const result = await callSkill('spec-bootstrap', 'tasks', {
          planFile: args.planFile ?? 'specs/001-feature/plan.md',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_analyze': {
        const result = await callSkill('spec-bootstrap', 'analyze', {
          feature: args.feature ?? '001-feature',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_bootstrap_implement': {
        const result = await callSkill('spec-bootstrap', 'implement', {
          taskId: args.taskId,
          phase: args.phase,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'scaffold_runner_run': {
        const result = await callSkill('scaffold-runner', 'run', {
          stack: args.stack,
          packageManager: args.packageManager ?? 'pnpm',
          projectName: args.projectName ?? '.',
          options: args.options ?? {},
        }, {
          timeoutMs: 180_000,
        });
        return formatSkillResult(result);
      }

      case 'code_patterns_generate': {
        const result = await callSkill('code-patterns', 'generate', {
          pattern: args.pattern,
          framework: args.framework ?? 'typescript',
          section: args.section ?? 'all',
          asFormat: args.asFormat ?? 'prompt',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'ui_design_adjust': {
        const result = await callSkill('ui-design', 'adjust', {
          instruction: args.instruction,
          filePath: args.filePath,
          autoApply: args.autoApply ?? false,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'spec_userstory_to_design_generate': {
        const result = await callSkill('spec-userstory-to-design', 'generate', {
          featureName: args.featureName,
          specFile: args.specFile,
          outputDir: args.outputDir,
          format: args.format ?? 'all',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'api_contract_generate': {
        const result = await callSkill('api-contract', 'generate', {
          fromFiles: args.fromFiles,
          name: args.name,
          outputPath: args.outputPath ?? 'contracts/openapi.yaml',
          authType: args.authType ?? 'jwt',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'html_converter_convert': {
        const result = await callSkill('html-converter', 'convert', {
          htmlFile: args.htmlFile,
          framework: args.framework,
          name: args.name,
          typescript: args.typescript ?? true,
          splitThreshold: args.splitThreshold ?? 3,
          outputDir: args.outputDir ?? 'components',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      // ============ Phase 2: 功能变更与实现 ============
      case 'openspec_workflow_propose': {
        const result = await callSkill('openspec-workflow', 'propose', {
          title: args.changeName,
          description: args.intent,
          baseFeature: args.baseFeature ?? 'main',
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'implement_executor_run': {
        const result = await callSkill('implement-executor', 'run', {
          taskId: args.taskId,
          featureId: args.featureId,
          phase: args.phase,
          maxRetries: args.maxRetries ?? 3,
          dryRun: args.dryRun ?? false,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 300_000,
        });
        return formatSkillResult(result);
      }

      case 'implement_executor_resume': {
        const result = await callSkill('implement-executor', 'resume', {
          featureId: args.featureId,
          skipFailedTasks: args.skipFailedTasks ?? false,
          fromPhase: args.fromPhase ?? null,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 300_000,
        });
        return formatSkillResult(result);
      }

      case 'implement_executor_status': {
        const result = await callSkill('implement-executor', 'status', {
          featureId: args.featureId,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 30_000,
        });
        return formatSkillResult(result);
      }

      case 'implement_executor_rollback': {
        const result = await callSkill('implement-executor', 'rollback', {
          featureId: args.featureId,
          toHead: args.toHead ?? null,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 30_000,
        });
        return formatSkillResult(result);
      }

      case 'test_runner_run': {
        const result = await callSkill('test-runner', 'run', {
          phase: args.phase,
          scope: args.scope ?? 'all',
          failOnCoverageBelow: args.failOnCoverageBelow ?? 80,
          updateBaseline: args.updateBaseline ?? false,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 240_000,
        });
        return formatSkillResult(result);
      }

      case 'git_workflow_commit': {
        const result = await callSkill('git-workflow', 'commit', {
          files: args.files,
          message: args.message,
          taskId: args.taskId,
          storyId: args.storyId,
          signoff: args.signoff ?? false,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'git_workflow_pr': {
        const result = await callSkill('git-workflow', 'pr', {
          feature: args.feature,
          base: args.base ?? 'main',
          reviewers: args.reviewers ?? [],
          labels: args.labels ?? ['feature', 'auto-generated'],
          draft: args.draft ?? true,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      // ============ Phase 3: 质量保障 ============
      case 'debug_helper_analyze': {
        const result = await callSkill('debug-helper', 'analyze', {
          errorMessage: args.errorMessage,
          stackTrace: args.stackTrace,
          logFile: args.logFile,
          context: args.context,
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'review_checklist_review': {
        const result = await callSkill('review-checklist', 'review', {
          prNumber: args.prNumber,
          base: args.base ?? 'main',
          strictMode: args.strictMode ?? true,
          categories: args.categories,
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 180_000,
        });
        return formatSkillResult(result);
      }

      case 'dependency_auditor_audit': {
        const result = await callSkill('dependency-auditor', 'audit', {
          addPackage: args.addPackage,
          ecosystem: args.ecosystem ?? 'npm',
          failOnLicense: args.failOnLicense ?? ['GPL-3.0', 'AGPL-3.0'],
          projectRoot: PROJECT_ROOT,
        });
        return formatSkillResult(result);
      }

      case 'environment_manager_inject': {
        const result = await callSkill('environment-manager', 'inject', {
          env: args.env,
          keys: args.keys ?? [],
          target: args.target ?? 'process',
          backend: args.backend ?? 'dotenv',
          projectRoot: PROJECT_ROOT,
        }, {
          timeoutMs: 30_000,
        });
        return formatSkillResult(result);
      }

      default:
        return {
          isError: true,
          content: [{ type: 'text', text: `Unknown tool: ${name}` }],
        };
    }
  } catch (error: any) {
    log(`Tool ${name} exception: ${error.message}`);
    return {
      isError: true,
      content: [{ type: 'text', text: `Tool ${name} failed: ${error.message}` }],
    };
  }
});

// ============================================================
// 格式化 Skill 返回结果为 MCP 响应
// ============================================================

function formatSkillResult(result: SkillResult) {
  if (result.ok && result.data) {
    const dataStr = JSON.stringify(result.data, null, 2);
    const warnings = result.warnings?.length
      ? `\n⚠️ Warnings:\n${result.warnings.map(w => `  - ${w}`).join('\n')}`
      : '';
    const next = result.nextActions?.length
      ? `\n📋 Next Actions:\n${result.nextActions.map(a => `  - ${a}`).join('\n')}`
      : '';
    const duration = result.duration ? ` (${result.duration}ms)` : '';
    const summary = result.data.summary || result.data.message || '';

    return {
      content: [{
        type: 'text',
        text: `✅ ${result.command}${duration}\n\n${summary}${warnings}${next}\n\n📦 Data:\n${dataStr}`,
      }],
    };
  }

  return {
    isError: true,
    content: [{
      type: 'text',
      text: `❌ ${result.command}\n\nError: ${result.error || 'Unknown error'}`,
    }],
  };
}

// ============================================================
// 启动 Server
// ============================================================

const transport = new StdioServerTransport();

await server.connect(transport);

log(`orchestrator-tools MCP server started`);
log(`PROJECT_ROOT: ${PROJECT_ROOT}`);
log(`SKILL_BUNDLE_PATH: ${SKILL_BUNDLE_PATH}`);
log(`SKILL_CLI_BIN: ${SKILL_CLI_BIN}`);
log(`CLI exists: ${existsSync(SKILL_CLI_BIN)}`);
